### PR TITLE
Add discrete crit chance to gauntlet match panels

### PR DESCRIPTION
**Pull request by paulbilnoski**

### CODE REVIEW

**Comment by paulbilnoski** [comment]
Seeks to correct issues from request #134

**Comment by paulbilnoski** [comment]
Spelling mistake was reported in #143

**Comment by paulbilnoski** [comment]
Build might have failed due to a regression with package.json:99, which should have "sttapi": "file:STTApi", but was reverted back to "sttapi": "file:sttapi",

**Comment by IAmPicard** [comment]
Sorry, ignore the travis errors, I'm just trying to stand it up now, not related to your PR

**Comment by IAmPicard** [comment]
Thanks!

**Pull request merged**
